version: '3.2'
services:
    db:
        image: mongo:latest
        container_name: db-brainly
        restart: always
        ports:
            - ${MONDO_DB_PORT}:27017
        environment:
            MONGO_INITDB_DATABASE: brainly-cerebro
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
