version: '3.2'
services:
    db:
        image: mysql:8.0
        container_name: db-brainly
        restart: always
        ports:
            - ${TYPEORM_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
